@extends('errors.layout')
@section('title', 'Page Not Found')
@section('code', '404')
@section('heading', 'Page Not Found')
@section('message', 'The page you are looking for doesn\'t exist or has been moved.')
