@extends('errors.layout')
@section('title', 'Server Error')
@section('code', '500')
@section('heading', 'Something Went Wrong')
@section('message', 'An unexpected error occurred. Please try again or contact support.')
